### ISSUE TITLE
anchor.init.js

### ISSUE THREAD

**Issue by davdenic** [cbopp-art/anchor#4]
Hi in the readme you wrote about anchor.init.js which is not available in the the repo.
thanks :-)

**Comment by cbopp-art** [comment]
Thanks for reporting. :)
I will adjust the documentation asap.

**Comment by tuffstudio** [comment]
yeah anchor.init.js isn't in the repo

**Comment by cbopp-art** [comment]
@davdenic Installation guide is up to date now.
