### ISSUE TITLE
Do you think you could add this to a cdn?

### ISSUE THREAD

**Issue by bearcott** [cbopp-art/anchor#5]
That would be awesome....

**Comment by cbopp-art** [comment]
Of course!
I did a new release v1.0.6 from state of master branch where an npm manifest file `package.json` with meta data already exists and I also created a new request to cdnjs for this plugin.
See: https://github.com/cdnjs/cdnjs/issues/6667

**Comment by bearcott** [comment]
Thanks! Appreciate.
