### ISSUE TITLE
The confirmation of license version

### ISSUE THREAD

**Issue by Piicksarn** [cbopp-art/anchor#6]
@cbopp-art :smiley: 
The license version shown in package.json is **`GPL-2.0+`**, however, it is **`GPL-3.0`** in license.txt.
would you help me for confirming the license version, so that it could be added in [cdnjs](https://github.com/cdnjs/cdnjs)

The reference PR: https://github.com/cdnjs/cdnjs/pull/7435

Thank a lot !
Piicksarn

**Comment by cbopp-art** [comment]
Hi!

anchor.js is under GPL 2.0 but also later licence versions.

Cornel
